name: Vaults
version: ${version}
main: com.BreiwalkerSMP.Vaults.Vaults
api-version: '1.21.5'
authors: [Breiwalker]

libraries:
  - org.xerial:sqlite-jdbc:3.46.0.0

commands:
  vault:
    description: Open your vault
    usage: /vault [share|shared|<player>]
permissions:
  vaults.admin:
    description: Open any player's vault
    default: op
  vaults.update:
    description: Receive update notifications
    default: op