name: Vaults
version: ${version}
main: com.BreiwalkerSMP.Vaults.Vaults
api-version: '1.21.5'
folia-supported: true
commands:
  vault:
    description: Open or share your vault.
    usage: /vault [player|share|shared]